#!/bin/bash

# ========== variables ==========
argCount=$#
helpExist=false
listExist=false
countExist=false
# ===============================

# if no command line arguments, then echo and exit
if [ $argCount -eq 0 ]; then
  echo "The usage of this command is: backup [options] targetFileList"
fi 

# iterate over command line arguments
# if '$var' matches any key command, mark the command as true
for var in "$@"
do
  if [ "$var" == "--help" ]; then
    helpExist=true
  elif [ "$var" == '-l' ]; then
    listExist=true
  elif [ "$var" == '-n' ]; then
    countExist=true
  elif [ "$var" == '-nl' ] || [ "$var" == '-ln' ]; then
    listExist=true
    countExist=true
  elif [[ "$var" == -* ]]; then
    echo "backup: invalid option $var"
  elif [ -f "$var" ]; then
    if [ ! -d ~/.backup ]; then
      mkdir ~/.backup
    fi
    cp $var ~/.backup
    echo "$var in .backup"
  elif [ -d "$var" ]; then
    if [ ! -d ~/.backup ]; then
      mkdir ~/.backup
    fi
    cp -R $var ~/.backup
    echo "$var in .backup"
  else
    echo "Cannot find file/directory: $var"
  fi
done


# list
if [ "$listExist" == true ]; then
  echo "================================"
  echo "File List in .backup:"
  ls ~/.backup
  echo "================================"
fi

# count
if [ "$countExist" == true ]; then
  echo "================================"
  echo "Number of files in .backup: $count"
  ls ~/.backup | wc -l 
  echo "================================"
fi

# help
if [ "$helpExist" == true ]; then
  echo "|==================================================|"
  echo "|                   Help Menu                      |"                                       
  echo "|--------------------------------------------------|"
  echo "| This script is used to quickly backup your files |"
  echo "| and directories.                                 |"
  echo "| -------------------------------------------------|"
  echo "| Script Format:                                   |"
  echo "| backup [options] targetFileList                  |"
  echo "| -------------------------------------------------|"
  echo "| Options:                                         |"
  echo "| -l --------> list files in backup directory      |"
  echo "| -n --------> number of files in backup directory |"
  echo "| -nl -ln ---> list files and number of files in   |"
  echo "|              backup directory                    |"
  echo "| --help ----> show help menu                      |"
  echo "| =================================================|"
fi